name: Diff Files

on:
  push:
    paths:
      - 'test/**'

jobs:
  diff_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Diff files and generate error output
        run: |
          mkdir -p err
          datetime=$(date '%m%d')
          for file in $(git diff --name-only HEAD^ HEAD --diff-filter=AM -- test/); do
            filename=$(basename "$file")
            diff -y --suppress-common-lines "ref/$filename" "test/$filename" > "err/$filename.$datetime.err"
          done
